version: '3'
services:
  lamp:
    build: ./
    # restart: always
    user: "1000:1000"
    ports:
      - 8080:80
    depends_on:
      - maildev
      - db
      - minio
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/more_upload_size.ini
      - ../../:/var/www/html
  maildev:
    image: maildev/maildev:1.1.0
    # restart: always
    ports:
      - 8081:80
      - 25:25
  db:
    image: mariadb:10.8.3
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    # restart: always
    depends_on:
      - db
    ports:
      - 8000:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=access1234
      - MINIO_ROOT_PASSWORD=secret1234
    command: server /data --console-address ":9001"
    volumes:
      - ./.file:/data
